version: '3.3'

services:
  database:
    restart: unless-stopped
    image: postgis/postgis
    env_file:
      - ./server/.env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  geoserver:
    restart: unless-stopped
    depends_on:
      - database
    image: thinkwhere/geoserver
    volumes:
      - ./data/geoserver:/opt/geoserver/data_dir
    ports:
      - '8080:8080'

  api:
    restart: unless-stopped
    depends_on:
      - database
    build: ./server
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=5000
    env_file:
      - ./server/.env

  nginx:
    restart: unless-stopped
    depends_on:
      - api
    build: ./nginx
    ports:
      - '80:80'
