version: '3'

services:
  database:
    image: postgis/postgis
    env_file:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=geoapp
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  geoserver:
    depends_on:
      - database
    image: thinkwhere/geoserver
    volumes:
      - ./geoserver_data:/opt/geoserver/data_dir
    ports:
      - '8080:8080'

  api:
    depends_on:
      - database
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - DATABASE_URI=postgres://postgres:postgres@database:5432/geoapp
      - ADMIN_JWT_SECRET=jdsaoiwjq91uoidj1djaosidj120
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - '5000:5000'

  nginx:
    depends_on:
      - api
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - '80:80'
